spring:
  datasource:
    url: jdbc:h2:mem:appdb
    username: hb
    password:
  h2:
    console:
      path: /h2
      enabled: true
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    generate-ddl: true
    show-sql: true